spring:
  datasource:
    url: jdbc:postgresql://postgres_parkle:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: redis_parkle
      port: 6379

  security:
    bcrypt:
      strength: ${SPRING_SECURITY_BCRYPT_STRENGTH}

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: never

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
