server:
  forward-headers-strategy: native

spring:
  application:
    name: Parkle Project Jun 2025

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /api-docs
