spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/start_page_test_db
    username: cock
    password: cockMaster

  redis:
    host: localhost
    port: 6379

  security:
    bcrypt:
      strength: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
jwt:
  secret-key: RjZkNHd5N3pAJ0MoRitKQE5jUmZValhuMnI1dTh4L0E
  expiration: 200000000
